formatter: "markdown table"
output:
  file: "README.md"
  mode: inject
recursive:
  enabled: true
  path: modules
sections:
  show:
    - requirements
    - providers
    - modules
    - resources
    - data-sources
    - inputs
    - outputs
